
modLoader="javafml" #mandatory
loaderVersion="[43,)"

license="MIT"

[[mods]] #mandatory

modId="hadeancraft" #mandatory

version="1.19.2" #mandatory
 
displayName="HadeanCraft" #mandatory

logoFile="examplemod.png" #optional

authors="Potassium" #optional

#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''
A simple mod made by me Potassium
Hope you enjoy it :)
'''

[[dependencies.hadeancraft]] #optional
  
    modId="forge" #mandatory
    
    mandatory=true #mandatory
   
    versionRange="[43,)" #mandatory
    
    ordering="NONE"
    
    side="BOTH"

[[dependencies.hadeancraft]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.0.0,1.19.2)"
    ordering="NONE"
    side="BOTH"
